[package]
name = "typst-shell-escape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = "0.12.0"
libc = "0.2"
serde_json = "1.0"
wait-timeout = "0.2"
